plugins:
  - remark-preset-lint-consistent
  - remark-preset-lint-recommended
  - remark-preset-lint-markdown-style-guide
  - ["remark-lint-no-multiple-toplevel-headings", false]
  - ["remark-lint-table-pipe-alignment", false]
